version: 2

updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - content

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 99
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 99
    groups:
      dependencies:
        patterns:
          - '*'
